#!/usr/bin/env python3
"""canon の keymap の &vkey <id> から chord の [v-key-aliases] ブロックを生成。

キーマップが「どの物理キーがどの vkey id を送るか」の唯一のソース。

imprint (config/imprint.keymap) — id は (層, QWERTY 位置) を完全エンコードする:
  - 0x01                  … DEFAULT 層の単体 X_1 (alias: VK_X1)
  - base 0x10/0x30/0x50/0x70 = LL/LM/RM/RR 層、(id - base) = QWERTY 位置 0..29
    → KEYS[位置] のキー名 → alias TU_<層>_<キー>（X_1 → X1 等、'_' は除去）
  ※ pos は 0..29 で nibble をまたぐ（例 LL の C は 0x10+22 = 0x26）ため、層は
    & 0xF0 ではなく base ≤ id < base+30 の **レンジ判定**で復号する。

復号した結果を [v-key-aliases] ブロックにして config/vkey-aliases.toml へ書く。
出力は chord (dotfiles) の config へ貼る用（chord 側 chezmoi 運用は各自）。

  python3 scripts/gen-vkey-aliases.py           # 生成して config/vkey-aliases.toml を更新
  python3 scripts/gen-vkey-aliases.py --check    # キーマップと生成物がずれてたら exit 1 (CI 用)

stdlib のみ。リポジトリルートからの相対パスで動く。
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KEYMAP = ROOT / "config" / "imprint.keymap"
OUT = ROOT / "config" / "vkey-aliases.toml"

# --- imprint: (層, QWERTY 位置) → alias --------------------------------------
# QWERTY 読み順 0..29 = 各 T_*_LAYER の 30 キー（canon キーボードの物理配列）。
KEYS = ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P",
        "A", "S", "D", "F", "G", "H", "J", "K", "L", "X_1",
        "Z", "X", "C", "V", "B", "N", "M", "X_2", "X_3", "X_4"]
# 層ごとの base（出力順もこの順）。各層は base..base+29 を占める。
# ※ 0xA0..0xBF は別 repo の ist 受信ドングル製品向けに **予約**（canon では未使用）。
#   chord は vkey id → action をホスト単位の 1 つの名前空間で解決するため、
#   この帯を imprint へ広げると ist のボタンが誤爆する。decode() は構造的に拒否する。
LAYERS = [("LL", 0x10), ("LM", 0x30), ("RM", 0x50), ("RR", 0x70)]
VK_X1_ID = 0x01

VKEY_RE = re.compile(r"&vkey\s+(0[xX][0-9A-Fa-f]+|\d+)")

HEADER = (
    "# AUTO-GENERATED by scripts/gen-vkey-aliases.py from config/imprint.keymap — do not edit.\n"
    "# canon キーマップの &vkey <id> を chord の論理名へ。`cat config/vkey-aliases.toml`\n"
    "# のこのブロックを chord config (dotfiles) の [v-key-aliases] に貼る（chezmoi は各自運用）。"
)


def parse_id(token: str) -> int:
    return int(token, 16) if token.lower().startswith("0x") else int(token)


def strip_comments(text: str) -> str:
    """C 風コメント（/* */ と //）を除去。コメント内の例コードを拾わないため。"""
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def alias_name(layer: str, key: str) -> str:
    return f"TU_{layer}_{key.replace('_', '')}"


def decode(vid: int) -> str:
    """imprint vkey id → alias 名。不正な id は SystemExit。"""
    if vid == VK_X1_ID:
        return "VK_X1"
    for layer, base in LAYERS:
        if base <= vid < base + len(KEYS):
            return alias_name(layer, KEYS[vid - base])
    raise SystemExit(
        f"vkey id 0x{vid:02X}: どの層レンジにも該当しない"
        f"（期待 0x01 or {', '.join(f'0x{b:02X}..0x{b + len(KEYS) - 1:02X}' for _, b in LAYERS)}）"
    )


def collect_ids() -> list[int]:
    """imprint keymap の &vkey id（出現順、重複検出付き）。"""
    text = strip_comments(KEYMAP.read_text(encoding="utf-8"))
    ids = [parse_id(m) for m in VKEY_RE.findall(text)]
    if not ids:
        raise SystemExit("config/imprint.keymap に &vkey が見つからない")
    dup = sorted({v for v in ids if ids.count(v) > 1})
    if dup:
        raise SystemExit("imprint の &vkey id が重複: " + ", ".join(f"0x{v:02X}" for v in dup))
    return ids


def build() -> str:
    ids = collect_ids()                 # imprint（重複チェック済）
    name = {v: decode(v) for v in ids}  # 全 id を復号（不正なら decode が落ちる）
    # alias 名の重複検出（decode は単射だが、KEYS/LAYERS の打ち間違いは重複を生む。
    # 重複 key の TOML は不正なので大声で落とす）。
    all_names = list(name.values())
    dup_names = sorted({n for n in all_names if all_names.count(n) > 1})
    if dup_names:
        raise SystemExit("vkey alias 名が重複: " + ", ".join(dup_names))
    out: list[str] = [HEADER, "[v-key-aliases]"]
    if VK_X1_ID in name:
        out.append("# DEFAULT 単体 X_1")
        out.append(f"{name[VK_X1_ID]} = 0x{VK_X1_ID:02X}")
    for layer, base in LAYERS:
        grp = sorted(v for v in ids if base <= v < base + len(KEYS))
        if not grp:
            continue
        out.append(f"# T_{layer}_LAYER (base 0x{base:02X})")
        for v in grp:
            out.append(f"{name[v]} = 0x{v:02X}")
    return "\n".join(out) + "\n"


def main() -> int:
    new = build()
    if "--check" in sys.argv[1:]:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if new != cur:
            print(
                "config/vkey-aliases.toml が canon キーマップと同期していません。\n"
                "  python3 scripts/gen-vkey-aliases.py を実行してコミットしてください。",
                file=sys.stderr,
            )
            return 1
        print("vkey aliases は同期済み")
        return 0
    OUT.write_text(new, encoding="utf-8")
    print(f"updated {OUT.relative_to(ROOT)}  ({new.count(' = 0x')} aliases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
