#!/usr/bin/env python3
"""Generate chord's [v-key-aliases] table from the &vkey <id> bindings of the keymap.

config/imprint.keymap is the single source of which key sends which vkey id.
An id encodes (layer, QWERTY position):
  - 0x01: the base layer's X_1 key (alias VK_X1)
  - any other: the layer's base in LAYERS + the position, which indexes KEYS;
    alias TU_<layer>_<key> (X_1 -> X1: underscores dropped)
  A layer's positions cross a nibble boundary (LL's C is 0x10 + 22 = 0x26), so
  decode() finds the layer by the range base <= id < base + len(KEYS), not by
  id & 0xF0.

The table goes to config/vkey-aliases.toml, which is pasted into the chord
config (dotfiles).

  python3 scripts/gen-vkey-aliases.py          # rewrite config/vkey-aliases.toml
  python3 scripts/gen-vkey-aliases.py --check  # exit 1 when out of sync (CI)

Python stdlib only; paths are resolved from the repository root.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KEYMAP = ROOT / "config" / "imprint.keymap"
OUT = ROOT / "config" / "vkey-aliases.toml"

# QWERTY reading order: the &vkey keys of a T_*_LAYER, indexed by id - base.
KEYS = ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P",
        "A", "S", "D", "F", "G", "H", "J", "K", "L", "X_1",
        "Z", "X", "C", "V", "B", "N", "M", "X_2", "X_3", "X_4"]
# Base id of each layer, in output order; a layer takes len(KEYS) ids from it.
# 0xA0..0xBF is reserved for the ist dongle (another repository): chord maps
# vkey ids to actions in one namespace per host, so an imprint id in that band
# would fire ist's buttons. Keep every layer's range out of it: decode() then
# rejects those ids.
LAYERS = [("LL", 0x10), ("LM", 0x30), ("RM", 0x50), ("RR", 0x70)]
VK_X1_ID = 0x01

VKEY_RE = re.compile(r"&vkey\s+(0[xX][0-9A-Fa-f]+|\d+)")

HEADER = (
    "# AUTO-GENERATED by scripts/gen-vkey-aliases.py from config/imprint.keymap — do not edit.\n"
    "# chord's names for the keymap's &vkey ids: paste this table into the chord\n"
    "# config (dotfiles)."
)


def parse_id(token: str) -> int:
    return int(token, 16) if token.lower().startswith("0x") else int(token)


def strip_comments(text: str) -> str:
    """Drop /* */ and // comments, so that an &vkey inside a comment is not read."""
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def alias_name(layer: str, key: str) -> str:
    return f"TU_{layer}_{key.replace('_', '')}"


def decode(vid: int) -> str:
    """Alias of an imprint vkey id; exits on an id outside every range."""
    if vid == VK_X1_ID:
        return "VK_X1"
    for layer, base in LAYERS:
        if base <= vid < base + len(KEYS):
            return alias_name(layer, KEYS[vid - base])
    raise SystemExit(
        f"vkey id 0x{vid:02X} is in no layer range"
        f" (expected 0x01 or {', '.join(f'0x{b:02X}..0x{b + len(KEYS) - 1:02X}' for _, b in LAYERS)})"
    )


def collect_ids() -> list[int]:
    """The keymap's &vkey ids in order of appearance; exits on a duplicate."""
    text = strip_comments(KEYMAP.read_text(encoding="utf-8"))
    ids = [parse_id(m) for m in VKEY_RE.findall(text)]
    if not ids:
        raise SystemExit("config/imprint.keymap: no &vkey binding found")
    dup = sorted({v for v in ids if ids.count(v) > 1})
    if dup:
        raise SystemExit(
            "config/imprint.keymap: duplicate &vkey ids: " + ", ".join(f"0x{v:02X}" for v in dup)
        )
    return ids


def build() -> str:
    ids = collect_ids()
    name = {v: decode(v) for v in ids}
    # decode() is meant to be injective; a typo in KEYS or LAYERS would repeat
    # a name, and TOML rejects a duplicate key.
    all_names = list(name.values())
    dup_names = sorted({n for n in all_names if all_names.count(n) > 1})
    if dup_names:
        raise SystemExit("duplicate vkey alias names: " + ", ".join(dup_names))
    out: list[str] = [HEADER, "[v-key-aliases]"]
    if VK_X1_ID in name:
        out.append("# DEFAULT_LAYER X_1")
        out.append(f"{name[VK_X1_ID]} = 0x{VK_X1_ID:02X}")
    for layer, base in LAYERS:
        grp = sorted(v for v in ids if base <= v < base + len(KEYS))
        if not grp:
            continue
        out.append(f"# T_{layer}_LAYER (base 0x{base:02X})")
        for v in grp:
            out.append(f"{name[v]} = 0x{v:02X}")
    return "\n".join(out) + "\n"


def main() -> int:
    new = build()
    if "--check" in sys.argv[1:]:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if new != cur:
            print(
                "config/vkey-aliases.toml is out of sync with config/imprint.keymap.\n"
                "  Run python3 scripts/gen-vkey-aliases.py and commit the result.",
                file=sys.stderr,
            )
            return 1
        print("vkey aliases in sync")
        return 0
    OUT.write_text(new, encoding="utf-8")
    print(f"updated {OUT.relative_to(ROOT)}  ({new.count(' = 0x')} aliases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
